#!/bin/sh
#
# PROVIDE: bacula
# REQUIRE: DAEMON
#
. /etc/rc.subr

name="bacula"
rcvar=${name}_enable

BACULA_PATH=/usr/pbi/bacula-sd-$(uname -m)
BACULA_DB=${BACULA_PATH}/baculaUI/bacula.db
BACULA_SD=${BACULA_PATH}/sbin/bacula-sd
SQLITE3=${BACULA_PATH}/bin/sqlite3
command=/usr/local/bin/bacula-daemon

load_rc_config ${name}

: ${bacula_enable:="NO"}

bacula_stop()
{
	local port pidfile res restmp
	res=0
	echo -n 'Stopping bacula.'

	${SQLITE3} ${BACULA_DB} "SELECT
			baculasd_st_sdport
	 	FROM freenas_baculasdstorage" | \
	while read -r port; do
		pidfile=/var/run/bacula-sd.${port}.pid
		if [ -f "${pidfile}" ]
		then
			kill -KILL $(cat "${pidfile}")
			res=$((${res}+$?))
			rm -f ${pidfile}
		else
			killall -KILL bacula-sd
			res=$((${res}+$?))
		fi
	done

	echo
	return ${res}
}

bacula_start()
{

	local port
	service ix-bacula-sd start
	${SQLITE3} ${BACULA_DB} "SELECT
			baculasd_st_sdport
	 	FROM freenas_baculasdstorage" | \
	while read -r port; do
		${BACULA_SD} -c ${BACULA_PATH}/etc/bacula-sd.${port}.conf
	done

}

stop_cmd='bacula_stop'
start_cmd='bacula_start'
run_rc_command "$1"
